### ISSUE TITLE
问题: idx/grp 修改器

### ISSUE THREAD

**Issue by jerry54604** [ZhanruiLiang/jinyong-legend#1]
大神, 请问你用什么修改器来修改idx/grp文件?

**Comment by ZhanruiLiang** [comment]
我印象中是自己写了代码去pasre这个格式，没有用修改器也不需要修改。

**Comment by ZhanruiLiang** [comment]
And to clarify, this repo is just a fork. I didn't change anything on it. My own changes is in https://github.com/ZhanruiLiang/jinyong-legend-py
